#! /bin/bash

CONTAINER_NAME="grafana-dashboard"
if [ $(docker ps -a | grep $CONTAINER_NAME | awk '{print $NF}' | wc -l) -gt 0 ];then
	docker kill $CONTAINER_NAME
	docker rm $CONTAINER_NAME
fi
if [ -d "./logs" ];then
	rm -fr ./logs/*
fi

docker run -d -v /var/log/pilot:/var/log/supervisor \
    -p 80:80 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 \
    -v /pilot/elasticsearch:/opt/elasticsearch \
    -v /pilot/graphite/storage:/opt/graphite/storage \
    --name ${CONTAINER_NAME} registry.trufa.me:443/trufa/grafana:0.0.1
