#! /bin/bash

docker kill grafana-dashboard
docker rm grafana-dashboard
truncate ./logs/* --size 0

docker run -d -v $(pwd)/logs:/var/log/supervisor -p 80:80 -p 8125:8125/udp -p 8126:8126 -p 2003:2003 --name grafana-dashboard kamon/grafana_graphite
